package com.itheima.domain.cargo;

import java.util.Date;

public class HomePacing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.HOME_PACKING_LIST_ID
     *
     * @mbg.generated
     */
    private String homePackingListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.EXPORT_ID
     *
     * @mbg.generated
     */
    private String exportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.SELLER
     *
     * @mbg.generated
     */
    private String seller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.BUYER
     *
     * @mbg.generated
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.MARKS
     *
     * @mbg.generated
     */
    private String marks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.DESCRIPTIONS
     *
     * @mbg.generated
     */
    private String descriptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.CREATE_DEPT
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.HOME_PACKING_LIST_ID
     *
     * @return the value of co_home_packing_list.HOME_PACKING_LIST_ID
     *
     * @mbg.generated
     */
    public String getHomePackingListId() {
        return homePackingListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.HOME_PACKING_LIST_ID
     *
     * @param homePackingListId the value for co_home_packing_list.HOME_PACKING_LIST_ID
     *
     * @mbg.generated
     */
    public void setHomePackingListId(String homePackingListId) {
        this.homePackingListId = homePackingListId == null ? null : homePackingListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.EXPORT_ID
     *
     * @return the value of co_home_packing_list.EXPORT_ID
     *
     * @mbg.generated
     */
    public String getExportId() {
        return exportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.EXPORT_ID
     *
     * @param exportId the value for co_home_packing_list.EXPORT_ID
     *
     * @mbg.generated
     */
    public void setExportId(String exportId) {
        this.exportId = exportId == null ? null : exportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.SELLER
     *
     * @return the value of co_home_packing_list.SELLER
     *
     * @mbg.generated
     */
    public String getSeller() {
        return seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.SELLER
     *
     * @param seller the value for co_home_packing_list.SELLER
     *
     * @mbg.generated
     */
    public void setSeller(String seller) {
        this.seller = seller == null ? null : seller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.BUYER
     *
     * @return the value of co_home_packing_list.BUYER
     *
     * @mbg.generated
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.BUYER
     *
     * @param buyer the value for co_home_packing_list.BUYER
     *
     * @mbg.generated
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.MARKS
     *
     * @return the value of co_home_packing_list.MARKS
     *
     * @mbg.generated
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.MARKS
     *
     * @param marks the value for co_home_packing_list.MARKS
     *
     * @mbg.generated
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.DESCRIPTIONS
     *
     * @return the value of co_home_packing_list.DESCRIPTIONS
     *
     * @mbg.generated
     */
    public String getDescriptions() {
        return descriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.DESCRIPTIONS
     *
     * @param descriptions the value for co_home_packing_list.DESCRIPTIONS
     *
     * @mbg.generated
     */
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions == null ? null : descriptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.CREATE_BY
     *
     * @return the value of co_home_packing_list.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.CREATE_BY
     *
     * @param createBy the value for co_home_packing_list.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.CREATE_DEPT
     *
     * @return the value of co_home_packing_list.CREATE_DEPT
     *
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.CREATE_DEPT
     *
     * @param createDept the value for co_home_packing_list.CREATE_DEPT
     *
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.CREATE_TIME
     *
     * @return the value of co_home_packing_list.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.CREATE_TIME
     *
     * @param createTime the value for co_home_packing_list.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}