package com.itheima.dao.cargo;

import com.itheima.domain.cargo.HomePacing;
import com.itheima.domain.cargo.HomePacingExample;
import java.util.List;

public interface HomePackingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_home_packing_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String homePackingListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_home_packing_list
     *
     * @mbg.generated
     */
    int insert(HomePacing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_home_packing_list
     *
     * @mbg.generated
     */
    int insertSelective(HomePacing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_home_packing_list
     *
     * @mbg.generated
     */
    List<HomePacing> selectByExample(HomePacingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_home_packing_list
     *
     * @mbg.generated
     */
    HomePacing selectByPrimaryKey(String homePackingListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_home_packing_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HomePacing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_home_packing_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HomePacing record);
}